name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiNmQxMGU4M2QtOGYzOS00YTVhLTkwY2QtN2Q4OWMwODhkMDIyIiwidGVuYW50X2lkIjoiNjFjNGFmMzVlNmIwNjQ5NmFkY2E3YTk0ODM3ZDE2MmUyZDhhZTY1YmQ3Y2IwOTE2MWQyNTkzNjMyNmYyNjM5MyIsImludGVybmFsX3NlY3JldCI6IjFjODczNzkwLTZiNzAtNDU3ZS04YzcxLTAxZTZjYWM2YzBjMSJ9.vLjp2mH-4NU2WsbR0BVLLwPXeVsLPUGYZD7zTJDXodA"
JWT_SECRET="secret"

